//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesNote
    {
        public int Id { get; set; }
        public int id_user { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public System.DateTime date_creation { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
    
        public virtual UsersUser users_users { get; set; }
    }
}
